//var baseapiurl='ath.dataverse.gr:18090/api/';
var baseapiurl='http://www.kos.gr:90/api/';
var baseurl = 'http://www.kos.gr/';
var baseaccount="info@kos.gr";
var maxZoom = 16;
var minZoom = 12;
var categs = new Array();
categs[0]="";
categs[1]="shopping";
categs[2]="sights";
categs[3]="accomodation";
categs[4]="activities";
categs[5]="sea";
categs[6]="transport";
categs[7]="kos";
categs[8]="food";
categs[9]="kos";
categs[10]="entertainment";

