var enResources = {
		EmailHeading: "Fill your email:",
		Ok: "Ok",
		Skip:"Skip",   
		Back:"Back",
		ImportantEmail:"some comments",
		CurrentPosition:"Position",
		Places:"Places",
		Settings:"Settings",
		Tour:"Tour",
		SettingsHeading:"Change your settings",
		LanguageSelect:"Language:",
		EmailAccount:"Email Account:",
		EmailAccountPlaceholder:"email account",
		LoadAvailableTour:"Load Local Itineraries",
		LoadPortalTour:"Load Itineraries From Portal",
		FilterTour:"Load Itinerary",
		FilterPlaces:"Filter Places",
		Exit:"Exit",
		LoadFromPortal: "Load from Portal",
		LoadItinerary:"Load",
		LoadSelected:"Load selected to local disk",
		NotAvailableFiles:"There are no available tour files in sdcard.",
		EmailValidator:"You have to fill your email first!",
		AvailableInitiaries:"No available itineraries!",
		NoInternetAccess:"The application cannot access to the internet!",
		CurrentPosition:"You are here",
		ClearAll:"Clear all",
		Load:"Load / Continue",
		SaveChanges:"Save Changes"
};