var MyApp = MyApp || {};

MyApp.resources = {
		EmailHeading: "Fill your email:",
		Ok: "OK",
		Skip:"Skip",   
		Back:"Back",
		Apply:"Show on map",
		List:"List",
		Map:"Map",
		Filter:"Search",
		PBack:"Ok",
		ImportantEmail:"some comments",
		Places:"Explore",
		Settings:"Settings",
		Tour:"Tour",
		SettingsHeading:"Change your settings",
		LanguageSelect:"Language / Γλώσσα:",
		EmailAccount:"Email Account:",
		EmailAccountPlaceholder:"email account",
		LoadAvailableTour:"Load Local Itineraries",
		LoadPortalTour:"Load Itineraries From Portal",
		FilterTour:"Load Itinerary",
		FilterPlaces:"Select Categories",
		Exit:"Exit",
		LoadFromPortal: "Load from Portal",
		LoadItinerary:"Load",
		LoadSelected:"Load selected to local disk",
		NotAvailableFiles:"There are no available tour files in sdcard.",
		EmailValidator:"You have to fill your email first!",
		AvailableInitiaries:"No available itineraries!",
		NoInternetAccess:"No Internet Access!",
		CurrentPosition:"You are here",
		ClearAll:"Clear all",
		NoFilesFound:"No Itineraries found.",
		Load:"Show itinerary on map",
		SaveChanges:"Save Changes",
		UserMustBeOnLine:"Internet Connection needed to get directions",
		GetDirections:"Get directions",
		ShowNone:"Show none",
		MoreInfo:"More Ιnformation",
		CouldNotLoadItineraries:"Couldn't find itineraries for the specified email address",
		Hide:"hide",
		ShowPlaces:"Show places near you",
		placesPageHeader:"Select the category of places you would like to show on map",
		AwayFromKos:"Your current location is outside the island of Kos",
		ExitApp:"Are you sure you want to exit?",
		NoLocation:"Could not get your location",
		CouldNotGetFilesFromPortal:"Could not get files from portal",
		UpdateApp:"There is a new version of Kos.Mobile. Would you like to download it now?",
		Hide:"Close",
		ItineraryPageHeaderNull:'No Itineraries found in local memory. Use "Load from Portal" option to download tours from Portal',
		ItineraryPageHeaderOk:"Select from the following itineraries",
		Slider:"Select distance (km)",
		orderPlacesHeader:"Slide to filter places by distance from your current location",
		Refresh:"Refresh",
		Showing:"Showing ",
		From:" places out of ",
		HotelStars:"Filter Hotels by stars: ",
		RestaurantCuisine:"Filter restaurants by cuisine: ",
		PlacePoi:"Filter results by place: ",
		ArchaiologicalEra:"Filter Archaiological places by era: ",
		NightClubMusic:"Filter Night clubs by music: ",
		ShowAll:"All ",
		Stars:"Star(s)",
		FilterPopUpHeader:"Use the following filters",
        SearchPopUpHeader:"Search in the results",
		Cancel:"Cancel",
        FreeTextSearchLabel:"Use this text box for free text search",
		Website:"Website",
		Address:"Address",
		WholeIsland:"All",
		Place:"Place",
		Phone:"Phone",
		NoPointsNearBy:"No results found in radius less than ",
		Kilometers:" kilometers",
        FromYourPosition:" from your position.",
        Next:"Next",
        Explore:"Show information about more than 1200 points of interest!",
        Routes:"Show on map the routes that you planned on site.",
	Greek:"Ελληνικά"
};