var MyApp = MyApp || {};

MyApp.resources = {
		EmailHeading: "Fill your email:",
		Ok: "OK",
		Skip:"Skip",   
		Back:"Back",
		Apply:"Apply",
		PBack:"Ok",
		ImportantEmail:"some comments",
		CurrentPosition:"Position",
		Places:"Places",
		Settings:"Settings",
		Tour:"Tour",
		SettingsHeading:"Change your settings",
		LanguageSelect:"Language:",
		EmailAccount:"Email Account:",
		EmailAccountPlaceholder:"email account",
		LoadAvailableTour:"Load Local Itineraries",
		LoadPortalTour:"Load Itineraries From Portal",
		FilterTour:"Load Itinerary",
		FilterPlaces:"Filter Places",
		Exit:"Exit",
		LoadFromPortal: "Load from Portal",
		LoadItinerary:"Load",
		LoadSelected:"Load selected to local disk",
		NotAvailableFiles:"There are no available tour files in sdcard.",
		EmailValidator:"You have to fill your email first!",
		AvailableInitiaries:"No available itineraries!",
		NoInternetAccess:"The application cannot access to the internet!",
		CurrentPosition:"You are here",
		ClearAll:"Clear all",
		Load:"Show itinerary on map",
		SaveChanges:"Save Changes",
		UserMustBeOnLine:"You must connect to the Internet to get directions",
		GetDirections:"Get directions",
		ShowNone:"Show none",
		MoreInfo:"More Énformation",
		CouldNotLoadItineraries:"Couldn't find itineraries with the specified email address",
		Hide:"hide",
		ShowPlaces:"Show places near you",
		placesPageHeader:"Select the category of places you would like to show on map"
};