var grResources = {
        EmailHeading:"Καταχωρήστε το email σας:",
        Ok:"Εντάξει",
        Skip:"Παράκαμψη",   
        Back:"Επιστροφή",
        Apply:"Εμφάνιση στον χάρτη",
        PBack:"ΟK",
		List:"Λίστα",
		Map:"Χάρτης",
		Filter:"Αναζήτηση",
        ImportantEmail:"κάποια σχόλια",
        Places:"Εξερεύνηση",
        Settings:"Επιλογές",
        Tour:"Περιηγήσεις",
        SettingsHeading:"'Αλλαξε τις επιλογές σου",
        LanguageSelect:"Language / Γλώσσα:",
        EmailAccount:"Λογαριασμός Email:",
        EmailAccountPlaceholder:"λογαριασμός email",
        FilterTour:"Επιλογή Περιήγησης",
        LoadAvailableTour:"Φόρτωση Διαθέσιμων Περιηγήσεων",
        LoadPortalTour:"Φόρτωση Περιηγήσεων από Portal",
        FilterPlaces:"Φίλτρα Σημείων",
        Exit:"Έξοδος",
        LoadFromPortal: "Φόρτωση από Portal",
        LoadItinerary:"Φόρτωση",
        LoadSelected:"Φόρτωση επιλεγμένων στον δίσκο",
        NotAvailableFiles:"Δεν υπάρχουν διαθέσιμα αρχεία περιήγησης στην κάρτα μνήμης.",
        EmailValidator:"Πρέπει να συμπληρώσετε το email πρώτα!",
        AvailableInitiaries:"Δεν υπάρχουν διαθέσιμες περιηγήσεις!",
        NoInternetAccess:"Η εφαρμογή δεν έχει πρόσβαση στο Διαδίκτυο!",
        CurrentPosition:"Βρίσκεστε εδώ",
    	ClearAll:"Καθαρισμός",
    	NoFilesFound:"Δεν βρέθηκαν περιηγήσεις",
    	Load:"Προβολή στον χάρτη",
    	SaveChanges:"Αποθήκευση",
    	UserMustBeOnLine:"Πρέπει να είστε συνδεδεμένοι στο διαδίκτυο",
    	GetDirections:"Οδηγίες μέχρι εδώ",
    	ShowNone:"Εμφάνιση κανενός",
    	MoreInfo:"Περισσότερες πληροφορίες",
		CouldNotLoadItineraries:"Δεν βρέθηκαν περιηγήσεις με τη συγκεκριμένη διεύθυνση email",
		placesPageHeader:"Επιλέξτε την κατηγορία από τα μέρη που θέλετε να εμφανιστούν στον χάρτη",
		AwayFromKos:"Η θέση σας είναι εκτός ορίων του νησιού της Κω",
		ExitApp:"Έξοδος από την εφαρμογή;",
		NoLocation:"Δεν βρέθηκε η τοποθεσία σας",
		CouldNotGetFilesFromPortal:"Η επικοινωνία με τον server απέτυχε",
		UpdateApp:"Υπάρχει νέα έκδοση της εφαρμογής. Θέλετε να την κατεβάσετε;",
		Hide:"Κλείσιμο",
		ItineraryPageHeaderNull:'Δεν υπάρχουν διαθέσιμες περιηγήσεις στη μνήμη της συσκευής. Επιλέξτε "Φόρτωση από Portal" για να κατεβάσετε τις διαθέσιμες περιηγήσεις από την ιστοσελίδα',
		ItineraryPageHeaderOk:"Μπορείτε να επιλέξετε από τις ακόλουθες περιηγήσεις",
		Slider:"Επιλέξτε ακτίνα στον χάρτη (χλμ)",
		orderPlacesHeader:"Σύρετε την μπάρα για να επιλέξετε τα σημεία με βάση την απόσταση",
		Refresh:"Ανανέωση",
		Showing:"Εμφανίζονται ",
		From:" σημεία, από τα ",
		HotelStars:"Αναζήτηση Ξενοδοχείων με βάση τα αστέρια: ",
		RestaurantCuisine:"Αναζήτηση εστιατορείων με βάση την κουζίνα: ",
		ArchaiologicalEra:"Αναζήτηση Αρχαιολογικών χώρων με βάση την περίοδο: ",
		NightClubMusic:"Αναζήτηση Νυχτερινών κέντρων με βάση τη μουσική: ",
		ShowAll:"Όλα ",
		Stars:"Αστέρι(α)",
		FilterPopUpHeader:"Χρησιμοποιήστε τα ακόλουθα φίλτρα.",
        SearchPopUpHeader:"Αναζήτηση στα αποτελέσματα.",
		Cancel:"Ακύρωση",
        FreeTextSearchLabel:"Χρησιμοποιείστε το παρακάτω πεδίο κειμένου για αναζήτηση με ελεύθερο κείμενο.",
	Website:"Ιστοσελίδα",
	Address:"Διεύθυνση",
	Place:"Τόπος",
	Phone:"Τηλέφωνο"
};