var grResources = {
        EmailHeading:"Καταχωρήστε το email σας:",
        Ok:"Εντάξει",
        Skip:"Παράκαμψη",   
        Back:"Επιστροφή",
        Apply:"Εφαρμογή",
        PBack:"ΟK",
        ImportantEmail:"κάποια σχόλια",
        CurrentPosition:"Θέση",
        Places:"Αναζήτηση",
        Settings:"Επιλογές",
        Tour:"Περιήγηση",
        SettingsHeading:"'Αλλαξε τις επιλογές σου",
        LanguageSelect:"Γλώσσα:",
        EmailAccount:"Λογαριασμός Email:",
        EmailAccountPlaceholder:"λογαριασμός email",
        FilterTour:"Φόρτωση Περιήγησης",
        LoadAvailableTour:"Φόρτωση Διαθέσιμων Περιηγήσεων",
        LoadPortalTour:"Φόρτωση Περιηγήσεων από Portal",
        FilterPlaces:"Φίλτρα Σημείων",
        Exit:"Έξοδος",
        LoadFromPortal: "Φόρτωση από Portal",
        LoadItinerary:"Φόρτωση",
        LoadSelected:"Φόρτωση επιλεγμένων στον δίσκο",
        NotAvailableFiles:"Δεν υπάρχουν διαθέσιμα αρχεία περιήγησης στην κάρτα μνήμης.",
        EmailValidator:"Πρέπει να συμπληρώσετε το email πρώτα!",
        AvailableInitiaries:"Δεν υπάρχουν διαθέσιμες περιηγήσεις!",
        NoInternetAccess:"Η εφαρμογή δεν έχει πρόσβαση στο Διαδίκτυο!",
        CurrentPosition:"Βρίσκεστε εδώ",
    	ClearAll:"Καθαρισμός",
    	Load:"Φόρτωση περιήγησης",
    	SaveChanges:"Αποθήκευση",
    	UserMustBeOnLine:"Πρέπει να είστε συνδεδεμένοι στο διαδίκτυο",
    	GetDirections:"Οδηγίες μέχρι εδώ",
    	ShowNone:"Εμφάνιση κανενός",
    	MoreInfo:"Περισσότερες πληροφορίες",
		CouldNotLoadItineraries:"Δεν βρέθηκαν περιηγήσεις με τη συγκεκριμένη διεύθυνση email",
		placesPageHeader:"Επιλέξτε την κατηγορία από τα μέρη που θέλετε να εμφανιστούν στον χάρτη",
		AwayFromKos:"Η θέση σας είναι εκτός ορίων του νησιού της Κω",
		ExitApp:"Έξοδος από την εφαρμογή;",
		NoLocation:"Δεν βρέθηκε η τοποθεσία σας",
		CouldNotGetFilesFromPortal:"Η επικοινωνία με τον server απέτυχε"
};