var MyApp = MyApp || {};

MyApp.resources = {
		EmailHeading: "Fill your email:",
		Ok: "OK",
		Skip:"Skip",   
		Back:"Back",
		Apply:"Apply",
		PBack:"Ok",
		ImportantEmail:"some comments",
		CurrentPosition:"Position",
		Places:"Search",
		Settings:"Settings",
		Tour:"Tour",
		SettingsHeading:"Change your settings",
		LanguageSelect:"Language:",
		EmailAccount:"Email Account:",
		EmailAccountPlaceholder:"email account",
		LoadAvailableTour:"Load Local Itineraries",
		LoadPortalTour:"Load Itineraries From Portal",
		FilterTour:"Load Itinerary",
		FilterPlaces:"Filter Places",
		Exit:"Exit",
		LoadFromPortal: "Load from Portal",
		LoadItinerary:"Load",
		LoadSelected:"Load selected to local disk",
		NotAvailableFiles:"There are no available tour files in sdcard.",
		EmailValidator:"You have to fill your email first!",
		AvailableInitiaries:"No available itineraries!",
		NoInternetAccess:"No Internet Access!",
		CurrentPosition:"You are here",
		ClearAll:"Clear all",
		NoFilesFound:"No Itineraries found.",
		Load:"Show itinerary on map",
		SaveChanges:"Save Changes",
		UserMustBeOnLine:"Internet Connection needed to get directions",
		GetDirections:"Get directions",
		ShowNone:"Show none",
		MoreInfo:"More Énformation",
		CouldNotLoadItineraries:"Couldn't find itineraries for the specified email address",
		Hide:"hide",
		ShowPlaces:"Show places near you",
		placesPageHeader:"Select the category of places you would like to show on map",
		AwayFromKos:"Your current location is outside the island of Kos",
		ExitApp:"Are you sure you want to exit?",
		NoLocation:"Could not get your location",
		CouldNotGetFilesFromPortal:"Could not get files from portal",
		UpdateApp:"There is a new version of Kos.Mobile. Would you like to download it now?",
		Hide:"Close",
		ItineraryPageHeaderNull:"No Itineraries found",
		ItineraryPageHeaderOk:"You may select from the following itineraries"
};