var grResources = {
        EmailHeading:"Καταχωρήστε το email σας:",
        Ok:"Εντάξει",
        Skip:"Παράκαμψη",   
        Back:"Επιστροφή",
        ImportantEmail:"κάποια σχόλια",
        CurrentPosition:"Θέση",
        Places:"Σ.Ε.",
        Settings:"Επιλογές",
            Tour:"Περιήγηση",
            SettingsHeading:"'Αλλαξε τις επιλογές σου",
            LanguageSelect:"Γλώσσα:",
            EmailAccount:"Λογαριασμός Email:",
            EmailAccountPlaceholder:"λογαριασμός email",
            FilterTour:"Φόρτωση Περιήγησης",
            LoadAvailableTour:"Φόρτωση Διαθέσιμων Περιηγήσεων",
            LoadPortalTour:"Φόρτωση Περιηγήσεων από Portal",
            FilterPlaces:"Φίλτρα Σημείων",
            Exit:"Έξοδος",
            LoadFromPortal: "Φόρτωση από Portal",
            LoadItinerary:"Φόρτωση",
            LoadSelected:"Φόρτωση επιλεγμένων στον δίσκο",
                NotAvailableFiles:"Δεν υπάρχουν διαθέσιμα αρχεία περιήγησης στην κάρτα μνήμης.",
                EmailValidator:"Πρέπει να συμπληρώσετε το email πρώτα!",
                AvailableInitiaries:"Δεν υπάρχουν διαθέσιμες περιηγήσεις!",
                NoInternetAccess:"Η εφαρμογή δεν έχει πρόσβαση στο Διαδίκτυο!",
                CurrentPosition:"Βρίσκεστε εδώ.",
                	ClearAll:"Καθαρισμός σημείων",
                	Load:"Φόρτωση περιήγησης"

};